config/routes.rb
EHarvest::Application.routes.draw do
  devise_for :users

	root 'home#index'

  get '/agency_reports', controller: 'agency_reports', action: 'index'

  get 'agency', to: 'agencies#show'

  get 'shop', to: 'searches#new'

  resources :items
  resources :item_codes
  resources :agency_codes
  resources :locations
  resources :searches

  resources :orders do
    resources :order_items do
    end
  end

end

app/models/agency.rb
class Agency < ActiveRecord::Base
  has_many :users
  has_many :orders
  has_many :agency_reports
  has_and_belongs_to_many :locations, -> { uniq }
  has_and_belongs_to_many :agency_codes, -> { uniq }
end

app/models/agency_code.rb
class AgencyCode < ActiveRecord::Base
  has_and_belongs_to_many :agencies, -> { uniq }
  has_and_belongs_to_many :item_codes, -> { uniq }
end

app/models/agency_report.rb
class AgencyReport < ActiveRecord::Base
  belongs_to :report
  belongs_to :agency
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :item_code
  has_many :order_items


  before_save :to_lower

  def to_lower
    self.name = self.name.downcase
  end
  # This should be done by the database as well
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }

  # scope :for_agency, ->(agency_id) { where("items.id in
  #   (select id from item_codes inner join agency_codes_item_codes
  #     on (item_codes.id = agency_codes_item_codes.item_code_id)
  #     where agency_codes_item_codes.agency_code_id
  #     in ( select agency_code_id from agencies_agency_codes where agency_id = ? ))", agency_id) }

  # QUERY!
  # I wonder if there's a better way to do this. Probably is... :(
  # select * from items where items.id in
  # (select id from item_codes inner join agency_codes_item_codes
  #   on (item_codes.id = agency_codes_item_codes.item_code_id)
  #   where agency_codes_item_codes.agency_code_id
  #   in ( select agency_code_id from agencies_agency_codes where agency_id = 1 ));

end

app/models/item_code.rb
class ItemCode < ActiveRecord::Base
  has_many :items
  has_and_belongs_to_many :agency_codes, -> { uniq }
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :orders
  has_and_belongs_to_many :agencies, -> { uniq }
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :agency
  belongs_to :location
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :item
end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :agency_reports
end

app/models/search.rb
class Search < ActiveRecord::Base

  def items
    @items ||= find_items
  end
 
private
  def find_items
    items = Item.order(:name)
    items = items.where("name like ?", "%#{names.downcase}%") if names.present?
    items = items.where(category_id: category_id) if category_id.present?
    items
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :agency

  def is_admin?
    false
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  respond_to :html, :json
  before_action :authenticate_user!

  def index
    @orders = current_user.agency.orders
    respond_with(@orders)
  end

  def show
    @order = current_user.agency.orders.find(params[:id])
    respond_with(@order)
  end

  def edit
    @order = current_user.agency.orders.find(params[:id])
    respond_with(@order)
  end

  def new
    @order = current_user.agency.orders.new
    respond_with(@order)
  end

  def create
    @order = current_user.agency.orders.create(order_params)
    respond_with(@order)
  end

  def update
    @order = current_user.agency.orders.find(params[:id])
    @order.update(order_params)
    respond_with(@order)
  end

  def destroy
    current_user.agency.orders.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to orders_path }
      format.json { render json: true }
    end
  end

  def order_params
    params.require(:order).permit(:requester, :recipient, :location_id, :delivery_date)
  end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_codes_helper.rb
module ItemCodesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/orders/_add_order.html.erb
<div class="list-group-item">
	<div class="row">
		<div class="col-md-2">
			<br>
			<%= link_to "New Order", new_order_path, method: :get, class: "btn btn-primary btn-md btn-block " %>
			<br>
		</div>
		<div class="col-md-6">
			<br>
			<h4>Click the button to begin a new order.</h4>
		</div>
	</div>
</div>

app/views/orders/_order.html.erb
<div class="list-group-item">
	<div class="row">
		<div class="col-md-2">
			<h4>Status</h4>
			<p>Completed</p>
			<br>
			<%= link_to "View Details", order_path(order), class: "btn btn-primary btn-md btn-block" %>
		</div>
		<div class="col-md-4">
			<h4>Order #<%= order.id %></h3>
			<p><strong>Requested by:</strong> <%= order.requester %></p>
			<p><strong>Scheduled for:</strong> <%= order.delivery_date %></p> 
			<p><strong>Location:</strong> <%= order.location.name %></p>
			<p><strong>Recipient:</strong> <%= order.recipient %></p>
		</div>
	</div>
</div>

app/views/orders/_order_preview.html.erb
Awesome preview

app/views/orders/index.html.erb
<div class="container">
	<div class="row">
		<h1 class="text-center">Recent Orders</h1>
		<div class="list-group">
			<%= render "orders/add_order" %>
			<% if @orders.any? %>
				<% @orders.each do |order| %>
					<%= render order %>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/orders/new.html.erb
<h1> Create a New Order </h1>

<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>
    </div>
  <% end %>
  <ul>
        <p>
          <%= f.label :requested_by %><br />
          <%= f.text_field :requester %>
        </p>

        <p>
          <%= f.label :pick_up_person %><br />
          <%= f.text_field :recipient %>
        </p>
        <p>
          <%= f.label :scheduled_for %><br />
          <%= f.datetime_select :delivery_date , {:ampm => true} %>
        </p>

        <p>
          <%= f.label :pick_up_location %><br />
          <%= f.collection_select(:location_id, Location.all, :id, :name) %>
        </p>
      </ul>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/show.html.erb
<div class="list-group-item">
	<div class="row">
		<div class="col-md-2">
			<h4>Status</h4>
			<p>Completed</p>
		</div>
		<div class="col-md-4">
			<h4>Order #<%= @order.id %></h3>
			<p><strong>Requested by:</strong> <%= @order.requester %></p>
			<p><strong>Scheduled for:</strong> <%= @order.delivery_date.to_formatted_s(:long_date_local_time)  %></p> 
			<p><strong>Location:</strong> <%= @order.location.name %></p>
			<p><strong>Recipient:</strong> <%= @order.recipient %></p>
		</div>
	</div>
  <h4><%= link_to 'Shop for Items', new_search_path %></h4>
</div>
<br>
<div>
  <% @order.order_items.each do |i| %>
    <div class="list-group-item">
      <div class="row">
        <div class="col-md-4">
          <p><strong>Item:</strong> <%= i.item.name %></p>
        </div>
        <div class="col-md-2">
          <p><strong>Weight:</strong> <%= i.weight %></p>
        </div>
        <div class="col-md-2">
          <p><strong>Fee:</strong> $<%= number_with_precision(i.fee, precision: 2) %></p>
        </div>
        <div class="col-md-2">
          <p><strong>quantity:</strong> <%= i.quantity %></p>
        </div>
        <div class="col-md-2">
          <p><strong>total:</strong> $<%= number_with_precision(i.quantity * i.weight * i.fee, precision: 2) %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>