config/routes.rb
EHarvest::Application.routes.draw do
  devise_for :users

	root 'home#index'

  get '/agency_reports', controller: 'agency_reports', action: 'index'

  get 'agency', to: 'agencies#show'

  get 'shop', to: 'searches#new'

  resources :items
  resources :item_codes
  resources :agency_codes
  resources :locations
  resources :searches

  resources :orders do
    resources :order_items do
    end
  end

end

app/models/agency.rb
class Agency < ActiveRecord::Base
  has_many :users
  has_many :orders
  has_many :agency_reports
  has_and_belongs_to_many :locations, -> { uniq }
  has_and_belongs_to_many :agency_codes, -> { uniq }
end

app/models/agency_code.rb
class AgencyCode < ActiveRecord::Base
  has_and_belongs_to_many :agencies, -> { uniq }
  has_and_belongs_to_many :item_codes, -> { uniq }
end

app/models/agency_report.rb
class AgencyReport < ActiveRecord::Base
  belongs_to :report
  belongs_to :agency
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :item_code
  has_many :order_items


  before_save :to_lower

  def to_lower
    self.name = self.name.downcase
  end
  # This should be done by the database as well
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }

  # scope :for_agency, ->(agency_id) { where("items.id in
  #   (select id from item_codes inner join agency_codes_item_codes
  #     on (item_codes.id = agency_codes_item_codes.item_code_id)
  #     where agency_codes_item_codes.agency_code_id
  #     in ( select agency_code_id from agencies_agency_codes where agency_id = ? ))", agency_id) }

  # QUERY!
  # I wonder if there's a better way to do this. Probably is... :(
  # select * from items where items.id in
  # (select id from item_codes inner join agency_codes_item_codes
  #   on (item_codes.id = agency_codes_item_codes.item_code_id)
  #   where agency_codes_item_codes.agency_code_id
  #   in ( select agency_code_id from agencies_agency_codes where agency_id = 1 ));

end

app/models/item_code.rb
class ItemCode < ActiveRecord::Base
  has_many :items
  has_and_belongs_to_many :agency_codes, -> { uniq }
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :orders
  has_and_belongs_to_many :agencies, -> { uniq }
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :agency
  belongs_to :location
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :item
end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :agency_reports
end

app/models/search.rb
class Search < ActiveRecord::Base

  def items
    @items ||= find_items
  end
 
private
  def find_items
    items = Item.order(:name)
    items = items.where("name like ?", "%#{names.downcase}%") if names.present?
    items = items.where(category_id: category_id) if category_id.present?
    items
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :agency

  def is_admin?
    false
  end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_codes_helper.rb
module ItemCodesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/layouts/_header.html.erb
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span><span
                    class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href= <%= root_path %>>eHarvest</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">

                <li>
                    <%= link_to orders_path do %>
                        <span class="glyphicon glyphicon-home"></span>Orders
                    <% end %>
                </li>
                <li>
                    <%= link_to agency_reports_path do %>
                        <span class="glyphicon glyphicon-file"></span>Reports
                    <% end %>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"><span class="glyphicon glyphicon-user"></span>My Account</a></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </nav>
    <% #link_to image_tag("atlanta-food-bank.png", :border=>0), root_path %>
</div>

app/views/layouts/_login_form.html.erb
<%= form_for(resource, as resource_name, url: session_path(:user)) do |f| %>
	<h1>Welcome to eHarvest!</h1>
  <%= f.text_field :email %>
  <%= f.password_field :password %>
  <%= f.check_box :remember_me %>
  <%= f.label :remember_me %>
  <%= f.submit 'Sign in', class: "btn btn-md" %>
  <%= link_to "Forgot your password?", new_password_path(:user) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>eHarvest</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if params[:controller] == "home"  || params[:controller] == "devise/sessions" %>
		<div class="lander">
	<% else %>
		<%= render 'layouts/header' %>
	<% end %>

	<div class="container">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"<%= value %></div>
		<% end %>

		<%= yield %>
	</div>

	<% if params[:controller] == "home" %>
		</div>
	<% end %>


</body>
</html>

app/views/orders_items/_order_item.html.erb
<div class="item">
  <h2><%= link_to item.name, item %></h2>
  <div class="details">
    <%= number_to_currency(item.fee) %>
    
  </div>
</div>